name: cGAN_demo_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scikit-learn=1.2.2
  - scipy
  - jupyter
  - ipywidgets
  - pytorch
  - dill
  - pandas
  - pymatgen
  - onnxruntime
